# Generated by Django 5.2.4 on 2025-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlockedExercises',
            field=models.CharField(default=''),
        ),
    ]
