# Generated by Django 5.2.4 on 2025-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0002_customuser_unlockedexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='')),
                ('example', models.CharField(default='')),
                ('hints', models.CharField(default='')),
                ('test_file', models.CharField(default='')),
            ],
        ),
    ]
