# Generated by Django 4.2.23 on 2025-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0003_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("content", models.CharField(default="")),
                ("example", models.CharField(default="")),
            ],
        ),
    ]
