# Generated by Django 4.2.23 on 2025-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0004_theory"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="prompt",
            field=models.CharField(default=""),
        ),
    ]
