# Generated by Django 5.2.4 on 2025-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0006_qcm_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unlockedExercises',
        ),
        migrations.AddField(
            model_name='customuser',
            name='unlockedExercises',
            field=models.ManyToManyField(blank=True, to='CodeIslander.exercise'),
        ),
    ]
