# Generated by Django 4.2.23 on 2025-10-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0006_qcm_question_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theory",
            name="example",
        ),
        migrations.AlterField(
            model_name="theory",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="CodeIslander.theory",
                    ),
                ),
            ],
            options={
                "unique_together": {("theory", "number")},
            },
        ),
    ]
