# Generated by Django 5.2.4 on 2025-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0007_remove_customuser_unlockedexercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='example',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
