# Generated by Django 5.2.4 on 2025-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0008_alter_theory_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlockedQCM',
            field=models.ManyToManyField(blank=True, to='CodeIslander.qcm'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unlockedTheory',
            field=models.ManyToManyField(blank=True, to='CodeIslander.theory'),
        ),
    ]
