# Generated by Django 5.2.4 on 2025-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0009_customuser_unlockedqcm_customuser_unlockedtheory'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='exercisesUnlocked',
            field=models.ManyToManyField(blank=True, to='CodeIslander.exercise'),
        ),
    ]
