# Generated by Django 4.2.23 on 2025-10-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0007_remove_theory_example_alter_theory_content_example"),
        ("CodeIslander", "0010_theory_exercisesunlocked"),
    ]

    operations = []
