# Generated by Django 4.2.23 on 2025-10-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0011_merge_20251006_2227"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("csv_content", models.TextField()),
                (
                    "theory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="CodeIslander.theory",
                    ),
                ),
            ],
            options={
                "unique_together": {("theory", "number")},
            },
        ),
    ]
