# Generated by Django 4.2.23 on 2025-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0012_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="theory",
            name="chapter",
            field=models.CharField(default="", max_length=200),
        ),
    ]
