# Generated by Django 4.2.23 on 2025-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0013_theory_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="hints",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
