# Generated by Django 4.2.23 on 2025-10-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0014_alter_exercise_hints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="example",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="prompt",
            field=models.CharField(default="", null=True),
        ),
    ]
