# Generated by Django 4.2.23 on 2025-10-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0015_alter_exercise_example_alter_exercise_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="prompt",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
