# Generated by Django 4.2.23 on 2025-10-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeIslander", "0016_alter_exercise_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="solution",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
