# Generated by Django 5.2.4 on 2025-10-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0016_alter_exercise_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('test_type', models.CharField(max_length=50)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('stdin_data', models.TextField(blank=True, null=True)),
                ('except_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='CodeIslander.exercise')),
            ],
        ),
    ]
