# Generated by Django 5.2.4 on 2025-11-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0017_tests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='except_output',
            new_name='expected_ouput',
        ),
    ]
