# Generated by Django 5.2.4 on 2025-11-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0018_rename_except_output_tests_expected_ouput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='expected_ouput',
            new_name='expected_output',
        ),
    ]
