# Generated by Django 5.2.4 on 2025-11-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0019_rename_exercise_id_tests_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='test_file',
        ),
        migrations.AddField(
            model_name='exercise',
            name='function_to_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='module_name',
            field=models.CharField(default='user_code', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='example',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='hints',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
