# Generated by Django 5.2.4 on 2025-11-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0017_exercise_solution'),
        ('CodeIslander', '0020_remove_exercise_test_file_exercise_function_to_test_and_more'),
    ]

    operations = [
    ]
