# Generated by Django 5.2.4 on 2025-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0021_merge_20251102_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='solution',
        ),
        migrations.AddField(
            model_name='exercise',
            name='setup_code',
            field=models.TextField(blank=True, default='', help_text="Hidden code to run BEFORE the user's code (e.g., variable definitions)"),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='function_to_test',
            field=models.CharField(blank=True, help_text="Name of the function to test (e.g., 'add'). Leave blank for stdin/stdout programs.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='module_name',
            field=models.CharField(default='user_code', help_text="The module name to import. Default is 'user_code'.", max_length=100),
        ),
    ]
