# Generated by Django 5.2.4 on 2025-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeIslander', '0022_remove_exercise_solution_exercise_setup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='setup_files',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object of setup files: {"filename.txt": "content"}', null=True),
        ),
    ]
