from .security.register.activate import activate
from .security.register.activateEmail import activateEmail
from .pages.register import register
from .security.detailsChange.resetPassword.reset_confirmation import reset_confirmation
from .security.detailsChange.resetPassword.reset_password import reset_password
from .pages.user_home import user_home
from .pages.user_login import user_login
from .pages.user_logout import user_logout
from .pages.profile_view import profile_view
from .pages.welcome import welcome
from .security.detailsChange.resetEmail.reset_email import reset_email
from .security.detailsChange.reset_username import reset_username
from .security.detailsChange.resetEmail.changeEmail import changeEmail
from .security.detailsChange.resetEmail.activateChangeEmail import activateChangeEmail
from .security.totp.startTotp import startTotp
from .security.totp.enableTotp import enableTotp
from .security.totp.stopTotp import stopTotp
from .security.totp.disableTotp import disableTotp