# Generated by Django 5.2.4 on 2025-07-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='totpEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
