# Generated by Django 5.2.4 on 2025-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCode', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret',
            field=models.CharField(default=''),
        ),
    ]
