# Generated by Django 5.2.4 on 2025-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCode', '0003_customuser_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='secret',
            new_name='secretLogin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='secretTotp',
            field=models.CharField(default=''),
        ),
    ]
